# Generated by Django 5.1 on 2025-02-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.ImageField(blank=True, null=True, upload_to='title_image'),
        ),
    ]
