# Generated by Django 5.1 on 2025-02-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='title_image/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
