# Generated by Django 5.2.1 on 2025-05-12 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like_comment', '0003_alter_commentreply_comment'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.post'),
        ),
    ]
