# Generated by Django 5.1 on 2024-08-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture_url',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dedwheqpz/image/upload/v1724566164/Blog_Website/Profile_Picture/eilrzwzvrrp9axkpw1u5.jpg', null=True),
        ),
    ]
