# Generated by Django 5.1 on 2025-01-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_profile_picture_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created']},
        ),
    ]
