# Generated by Django 5.2.1 on 2025-05-12 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='received_reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
