# Generated by Django 5.2.1 on 2025-05-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_remove_review_received_reviews_review_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='post_count',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
